import js from '@eslint/js';
import { defineConfig } from 'eslint/config';
import prettier from 'eslint-config-prettier';
import { createTypeScriptImportResolver } from 'eslint-import-resolver-typescript';
import importX from 'eslint-plugin-import-x';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import playwright from 'eslint-plugin-playwright';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import testingLibrary from 'eslint-plugin-testing-library';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default defineConfig(
  {
    ignores: [
      'dist',
      'coverage',
      'playwright-report',
      'blob-report',
      'test-results',
      'reports',
      'public/mockServiceWorker.js', // generated by `msw init`
      '.stryker-tmp.stryker-tmp/sandbox-*',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.strictTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,

  {
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
      parserOptions: {
        projectService: {
          // Plain-JS config files sit outside the TS program but still deserve linting.
          allowDefaultProject: ['*.config.js'],
        },
        tsconfigRootDir: import.meta.dirname,
      },
    },
    settings: {
      // Resolves the `@/*` alias from tsconfig, so the layer rule below sees real
      // paths rather than unresolved specifiers it would silently skip.
      'import-x/resolver-next': [createTypeScriptImportResolver({ alwaysTryTypes: true, project: './tsconfig.json' })],
    },
    plugins: {
      'import-x': importX,
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
      'jsx-a11y': jsxA11y,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      ...jsxA11y.flatConfigs.recommended.rules,
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],

      /**
       * ============================================================
       * The layer dependency rule — the thing that keeps this repo navigable.
       *
       *     lib  ←  api  ←  hooks  ←  components · routes
       *
       * Written down in README.md, enforced here. A convention that only lives in a
       * document is a convention that decays; this one fails CI instead.
       *
       * `except` paths are relative to `from`.
       * ============================================================
       */
      'import-x/no-restricted-paths': [
        'error',
        {
          zones: [
            {
              target: './src/lib',
              from: './src',
              except: ['./lib'],
              message:
                'src/lib is the bottom layer: pure functions, no imports from other layers. This is what makes 100% coverage there cheap.',
            },
            {
              target: './src/api',
              from: './src',
              except: ['./lib', './api'],
              message: 'src/api may only import from src/lib. No React, no hooks, no components.',
            },
            {
              target: './src/hooks',
              from: './src',
              except: ['./lib', './api', './hooks'],
              message: 'src/hooks may only import from src/lib and src/api.',
            },
            {
              target: './src/components',
              from: './src',
              except: ['./lib', './components'],
              message:
                'A component that fetches cannot be rendered in a test without dragging the network along. Take data as props, or let a route call the hook.',
            },
          ],
        },
      ],
      'import-x/order': [
        'error',
        {
          groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index'],
          'newlines-between': 'always',
          alphabetize: { order: 'asc', caseInsensitive: true },
        },
      ],
      'import-x/no-cycle': 'error',

      '@typescript-eslint/consistent-type-imports': ['error', { fixStyle: 'inline-type-imports' }],
      '@typescript-eslint/no-unnecessary-condition': 'error',
      // Casting is how runtime type errors get past `tsc`. Parse at the boundary
      // instead — see docs/adr/0002-data-fetching-and-caching.md.
      '@typescript-eslint/consistent-type-assertions': ['error', { assertionStyle: 'never' }],
    },
  },

  /* ── Vitest test files ────────────────────────────────────────────────────── */
  {
    files: ['src/**/*.test.{ts,tsx}', 'src/test/**/*.{ts,tsx}'],
    ...testingLibrary.configs['flat/react'],
    rules: {
      ...testingLibrary.configs['flat/react'].rules,
      // Bans container.querySelector, direct node access, `cleanup` calls, and
      // awaiting sync queries — i.e. the ways a component test starts asserting on
      // implementation details instead of on what a user can perceive.
      'testing-library/no-container': 'error',
      'testing-library/no-node-access': 'error',
      'testing-library/prefer-user-event': 'error',
      'testing-library/prefer-explicit-assert': 'error',
      // Tests may assert on values the compiler thinks are always defined.
      '@typescript-eslint/no-unnecessary-condition': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
      // The layer rule constrains the *shipped* dependency graph: it is what stops a
      // component from fetching and what keeps src/lib pure enough to be worth gating
      // at 100%. A test importing src/test/handlers adds nothing to the bundle and
      // inverts no production dependency, so the rule has nothing to protect here.
      // Enforcing it anyway would push every test to restate its fixtures inline —
      // exactly the drift the shared factories exist to prevent.
      'import-x/no-restricted-paths': 'off',
    },
  },

  /* ── Playwright specs ─────────────────────────────────────────────────────── */
  {
    files: ['tests/**/*.spec.ts'],
    ...playwright.configs['flat/recommended'],
    rules: {
      ...playwright.configs['flat/recommended'].rules,
      // Determinism, enforced: no arbitrary sleeps, no conditional assertions.
      'playwright/no-wait-for-timeout': 'error',
      'playwright/no-conditional-in-test': 'error',
      'playwright/no-skipped-test': 'warn',
    },
  },

  /* ── Config files ─────────────────────────────────────────────────────────── */
  {
    files: ['*.config.{ts,js}', 'tests/**/*.ts'],
    rules: {
      'import-x/no-default-export': 'off',
      '@typescript-eslint/no-unnecessary-condition': 'off',
    },
  },

  /* ── Playwright fixtures ──────────────────────────────────────────────────── */
  {
    files: ['tests/**/*.ts'],
    rules: {
      // A Playwright fixture is `async ({ page }, use) => { await use(thing) }`. React
      // 19 added a hook also called `use`, and react-hooks cannot tell the two apart,
      // so it reports every fixture as a hook called outside a component. There is no
      // React in this directory at all — Playwright runs in Node, driving a browser.
      'react-hooks/rules-of-hooks': 'off',
    },
  },

  /* ── This file ────────────────────────────────────────────────────────────── */
  {
    files: ['eslint.config.js'],
    rules: {
      // Several ESLint plugins ship no TypeScript types, so every `plugin.configs.x`
      // read here is an `any` as far as the type-aware rules are concerned. Narrowly
      // disabled for this file only, rather than weakened repo-wide.
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
    },
  },

  // Must stay last: turns off every stylistic rule Prettier already owns.
  prettier,
);
